# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.com_layer1_clients_digital_model.create_staking_transaction_request import CreateStakingTransactionRequest

class TestCreateStakingTransactionRequest(unittest.TestCase):
    """CreateStakingTransactionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateStakingTransactionRequest:
        """Test CreateStakingTransactionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateStakingTransactionRequest`
        """
        model = CreateStakingTransactionRequest()
        if include_optional:
            return CreateStakingTransactionRequest(
                asset_pool_id = '',
                asset = 'TRX',
                network = 'TRON',
                type = 'STAKE',
                reference = 'myUniqueRef333',
                address = 'TNx5eZNjpmKw8s1a3GB1VBH246uf9V6pfe',
                amount = None,
                metadata = {
                    'key' : ''
                    }
            )
        else:
            return CreateStakingTransactionRequest(
        )
        """

    def testCreateStakingTransactionRequest(self):
        """Test CreateStakingTransactionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
