# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.fee_api import FeeApi


class TestFeeApi(unittest.TestCase):
    """FeeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeeApi()

    def tearDown(self) -> None:
        pass

    def test_estimate_transaction_fee(self) -> None:
        """Test case for estimate_transaction_fee

        Estimate transaction fee
        """
        pass


if __name__ == '__main__':
    unittest.main()
