# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.address_api import AddressApi


class TestAddressApi(unittest.TestCase):
    """AddressApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AddressApi()

    def tearDown(self) -> None:
        pass

    def test_create_address(self) -> None:
        """Test case for create_address

        Create a new address
        """
        pass

    def test_get_address(self) -> None:
        """Test case for get_address

        Get address
        """
        pass

    def test_list_addresses(self) -> None:
        """Test case for list_addresses

        List addresses
        """
        pass

    def test_list_tags(self) -> None:
        """Test case for list_tags

        List address tags
        """
        pass

    def test_validate_address(self) -> None:
        """Test case for validate_address

        Validate address
        """
        pass


if __name__ == '__main__':
    unittest.main()
