# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.transaction_request_api import TransactionRequestApi


class TestTransactionRequestApi(unittest.TestCase):
    """TransactionRequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionRequestApi()

    def tearDown(self) -> None:
        pass

    def test_create_staking_transaction(self) -> None:
        """Test case for create_staking_transaction

        Create staking transaction request
        """
        pass

    def test_create_transaction(self) -> None:
        """Test case for create_transaction

        Create transaction request
        """
        pass

    def test_get_transaction_request_by_id(self) -> None:
        """Test case for get_transaction_request_by_id

        Get transaction request
        """
        pass

    def test_list_transaction_requests(self) -> None:
        """Test case for list_transaction_requests

        List transaction requests
        """
        pass


if __name__ == '__main__':
    unittest.main()
