# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.key_pair_api import KeyPairApi


class TestKeyPairApi(unittest.TestCase):
    """KeyPairApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeyPairApi()

    def tearDown(self) -> None:
        pass

    def test_create_key_pair(self) -> None:
        """Test case for create_key_pair

        Create key pair
        """
        pass

    def test_get_key_pair(self) -> None:
        """Test case for get_key_pair

        Get key pair
        """
        pass

    def test_list_key_pairs(self) -> None:
        """Test case for list_key_pairs

        List key pairs
        """
        pass


if __name__ == '__main__':
    unittest.main()
