# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.screening_api import ScreeningApi


class TestScreeningApi(unittest.TestCase):
    """ScreeningApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScreeningApi()

    def tearDown(self) -> None:
        pass

    def test_list_screenings(self) -> None:
        """Test case for list_screenings

        List screening results
        """
        pass

    def test_manually_action_held_transfer(self) -> None:
        """Test case for manually_action_held_transfer

        Approve or reject a held transfer
        """
        pass


if __name__ == '__main__':
    unittest.main()
