# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.com_layer1_clients_digital_model.network_detail import NetworkDetail

class TestNetworkDetail(unittest.TestCase):
    """NetworkDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkDetail:
        """Test NetworkDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkDetail`
        """
        model = NetworkDetail()
        if include_optional:
            return NetworkDetail(
                block = openapi_client.models.block_detail.BlockDetail(
                    number = 123456, 
                    timestamp = '2021-01-01T00:00:00Z', ),
                fee = openapi_client.models.asset_value.AssetValue(
                    amount = null, 
                    asset = 'BTC', )
            )
        else:
            return NetworkDetail(
        )
        """

    def testNetworkDetail(self):
        """Test NetworkDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
