# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.com_layer1_clients_digital_model.manual_action_request import ManualActionRequest

class TestManualActionRequest(unittest.TestCase):
    """ManualActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManualActionRequest:
        """Test ManualActionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManualActionRequest`
        """
        model = ManualActionRequest()
        if include_optional:
            return ManualActionRequest(
                action = 'APPROVE',
                operation = 'DEPOSIT',
                reason = 'Confirmed false positive',
                transfer_id = '018f5bdd-ca48-70bd-9df1-daccba5e0dc0',
                address_id = '11e785c1-a31a-4de9-9585-351056bea639'
            )
        else:
            return ManualActionRequest(
                action = 'APPROVE',
                operation = 'DEPOSIT',
                reason = 'Confirmed false positive',
                transfer_id = '018f5bdd-ca48-70bd-9df1-daccba5e0dc0',
        )
        """

    def testManualActionRequest(self):
        """Test ManualActionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
