# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.transaction_api import TransactionApi


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionApi()

    def tearDown(self) -> None:
        pass

    def test_claim_transaction(self) -> None:
        """Test case for claim_transaction

        Claim blockchain transaction
        """
        pass

    def test_get_transaction_by_id(self) -> None:
        """Test case for get_transaction_by_id

        Get transaction
        """
        pass

    def test_list_transactions(self) -> None:
        """Test case for list_transactions

        List transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
