# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.network_api import NetworkApi


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkApi()

    def tearDown(self) -> None:
        pass

    def test_get_networks(self) -> None:
        """Test case for get_networks

        Get all networks
        """
        pass


if __name__ == '__main__':
    unittest.main()
