# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.asset_pool_api import AssetPoolApi


class TestAssetPoolApi(unittest.TestCase):
    """AssetPoolApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetPoolApi()

    def tearDown(self) -> None:
        pass

    def test_create_asset_pool(self) -> None:
        """Test case for create_asset_pool

        Create asset pool
        """
        pass

    def test_delete_asset_pool(self) -> None:
        """Test case for delete_asset_pool

        Delete asset pool
        """
        pass

    def test_get_asset_pool(self) -> None:
        """Test case for get_asset_pool

        Get asset pool
        """
        pass

    def test_get_asset_pool_balance(self) -> None:
        """Test case for get_asset_pool_balance

        Get asset pool balance
        """
        pass

    def test_get_asset_pool_max_withdrawable_amount(self) -> None:
        """Test case for get_asset_pool_max_withdrawable_amount

        Get max asset pool withdrawable balance
        """
        pass

    def test_get_asset_pool_summary(self) -> None:
        """Test case for get_asset_pool_summary

        Get asset pool summary
        """
        pass

    def test_list_asset_pools(self) -> None:
        """Test case for list_asset_pools

        List asset pools
        """
        pass

    def test_update_asset_pool(self) -> None:
        """Test case for update_asset_pool

        Update asset pool
        """
        pass


if __name__ == '__main__':
    unittest.main()
