# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com_layer1_clients_digital_api.return_api import ReturnApi


class TestReturnApi(unittest.TestCase):
    """ReturnApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReturnApi()

    def tearDown(self) -> None:
        pass

    def test_create_return_transaction_request(self) -> None:
        """Test case for create_return_transaction_request

        Create return transaction request
        """
        pass


if __name__ == '__main__':
    unittest.main()
