# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.com_layer1_clients_digital_model.create_address_request import CreateAddressRequest

class TestCreateAddressRequest(unittest.TestCase):
    """CreateAddressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAddressRequest:
        """Test CreateAddressRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAddressRequest`
        """
        model = CreateAddressRequest()
        if include_optional:
            return CreateAddressRequest(
                asset_pool_id = '',
                network = 'BITCOIN',
                asset = 'BTC',
                reference = 'myUniqueRef333',
                customer_id = 'customer123'
            )
        else:
            return CreateAddressRequest(
        )
        """

    def testCreateAddressRequest(self):
        """Test CreateAddressRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
