# coding: utf-8

"""
    Digital Asset

    Layer1 API making management of crypto assets simple and easy

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.com_layer1_clients_digital_model.block_detail import BlockDetail

class TestBlockDetail(unittest.TestCase):
    """BlockDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlockDetail:
        """Test BlockDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlockDetail`
        """
        model = BlockDetail()
        if include_optional:
            return BlockDetail(
                number = 123456,
                timestamp = '2021-01-01T00:00:00Z'
            )
        else:
            return BlockDetail(
        )
        """

    def testBlockDetail(self):
        """Test BlockDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
